### ISSUE TITLE
Build error on src/render_metal.rs:108

### ISSUE THREAD

**Issue by esimov** [repi/shadertoy-browser#2]
I'm getting the following error when i'm trying to build on MacOS:

`warning: variable does not need to be mutable
   --> src/render_metal.rs:108:25`

<img width="348" alt="screen shot 2018-01-06 at 6 23 53 pm" src="https://user-images.githubusercontent.com/883386/34641567-cba602dc-f30e-11e7-83c8-1540ecce4092.png">

I'm not a rust programmer, but I would like to try it out your rust application.

**Comment by repi** [comment]
Ah interesting, I was not seeing those warnings myself oddly enough. But they were valid and have fixed them now, thanks!

Which Rust toolchain version are you using? You can show that with `rustup show`, can you post the output of that here?

Those warnings should not be what failed the build for you though, looks like a C++ linking error, can you post the full text output from the build here?

**Comment by esimov** [comment]
This is what i got. And after this a long list of string with the error cause.

<img width="721" alt="screen shot 2018-01-06 at 7 42 35 pm" src="https://user-images.githubusercontent.com/883386/34642751-17c11f1e-f321-11e7-90ec-c66b12ada2a4.png">

**Comment by repi** [comment]
Oh, sounds like some Xcode issue with it not having the Metal framework installed or set up properly.

You could verify Xcode is installed and try and see if you can run any of the Xcode sample projects that use Metal

**Comment by esimov** [comment]
What i did: I installed macOS High Sierra in order to install the latest Xcode to get Metal 2. Now it's working nicely! Thanks for support and great work.

**Comment by repi** [comment]
Great!
