### ISSUE TITLE
Benchmark between GL and Metal

### ISSUE THREAD

**Issue by Michael-Lfx** [repi/shadertoy-browser#53]
Nice project. How is the performance differs from OpenGL And Metal? Which one is better? If is Metal, what times it will be faster than GL?

**Comment by repi** [comment]
This only supports Metal at this point and have no plan to add OpenGL support, esp. as OpenGL is deprecated in Mojave on Mac. Would be pretty easy to add GL support though for testing and for support on other platforms.

From a pure API PoV there wouldn't be any difference as it only does a single draw call perf frame so it is not CPU bound. There could and would likely be a difference between APIs based on the shader compiler stacks which are significantly different between GL and Metal (and the other APIs) that could result in GPU performance difference depending on how good the shader compiler compiles the very complex shader toy shaders.
