### ISSUE TITLE
catalina - error: failed to run custom build command for `shaderc v0.3.16`

### ISSUE THREAD

**Issue by 8secz-johndpope** [repi/shadertoy-browser#56]
Compiling aho-corasick v0.7.6
error: failed to run custom build command for `shaderc v0.3.16`

Caused by:
  process didn't exit successfully: `/Users/johndpope/Documents/gitWorkspace/shadertoy-browser/test/release/build/shaderc-8859e5aa0099e6c0/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at '

couldn't find required command: "cmake"

', /Users/johndpope/.cargo/registry/src/github.com-1ecc6299db9ec823/shaderc-0.3.16/build/cmd_finder.rs:45:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...

I tried appending  --target-dir to see if it helped - it didn't.
 **cargo build --release  --target-dir test**

**Comment by repi** [comment]
This lists the tools that are required to build `shaderc`: https://github.com/google/shaderc. You need cmake and python
