### ISSUE TITLE
Shaders run for 4 seconds and then hang.

### ISSUE THREAD

**Issue by adamnemecek** [repi/shadertoy-browser#59]
This is when I run "cargo run --release -- -s car".

**Comment by repi** [comment]
Get the same with latest and on Catalina. Probably a regression in either the libraries for the shader conversion, or in the graphics drivers themselves. Will  be hard to solve due to the complexity of shadertoy shaders.

**Comment by adamnemecek** [comment]
If I implement it, would you be interested in merging in a wgpu backend?

**Comment by repi** [comment]
Sure!

**Comment by adamnemecek** [comment]
I have built a shadertoy clone with rust and wgpu https://github.com/adamnemecek/shadertoy.
